"""db create

Revision ID: b67538e68ab7
Revises: 
Create Date: 2023-07-04 19:45:53.630905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b67538e68ab7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.Text(), nullable=True),
                    sa.Column('username', sa.Text(), nullable=True),
                    sa.Column('password_hash', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
    )
    op.create_table('operations',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('date', sa.Date(), nullable=True),
                    sa.Column('kind', sa.String(), nullable=True),
                    sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operations')
    op.drop_table('users')
    # ### end Alembic commands ###
